version: '3.8'

services:
  hrms-app:
    build: .
    ports:
      - "8577:8577"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8577
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - HRMS_UPLOAD_DIR=/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8577/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
